### ISSUE TITLE
Detected as Malware

### ISSUE THREAD

**Issue by AlanKK** [LeGeRyChEeSe/Sunshine-AIO#19]
See https://www.virustotal.com/gui/file/20eb8fab4d7b9c7c7c8c67aca787306bfcebb595dd3b1a3835ac2b7c414c950c

Chrome blocks download and many AV engines detect this as malware

**Comment by CommZod** [comment]
I've been really interested to try this out but the malware warnings on multiple levels set off my spidey sense. I remember seeing somewhere that the dev promised its not malware and is working on updating it so it doesn't detect as such.   However, i work in IT and have seen too many instances of Malware/ransomware,  I'll wait until it's not detected with the AV instead of "Trust me bro".

**Comment by LeGeRyChEeSe** [comment]
> See https://www.virustotal.com/gui/file/20eb8fab4d7b9c7c7c8c67aca787306bfcebb595dd3b1a3835ac2b7c414c950c
>
> Chrome blocks download and many AV engines detect this as malware

This a known issue because of the compiler used to compile my program.

There is no malware or anything else that could infect your pc, but if you're still not sure, I wrote a section in the repo for building the file by yourself, so you can ensure this is exactly the same file as the one shared in releases.

If you build it yourself like mentioned in this section, there will always be these false positives of viruses or malware when there are none.

I hope the next release should fix it, but for now on you just have to trust me, or build it yourself.

Also if you trust me or wanting to build it yourself, make sure to disable your antivirus software or add an exception to it for this file/folder.

**Comment by a-hersa** [comment]
There's no way I can download or execute the exe file on Windows

**Comment by LeGeRyChEeSe** [comment]
> There's no way I can download or execute the exe file on Windows

It’s because of your antivirus is enabled. Disable it temporarily to download the file, move the file to a folder you previously excluded in your antivirus and enable it again.

**Comment by a-hersa** [comment]
I disabled security on the browser and windows defender completely. It always flagged the installer and even if I managed to open it a few seconds, it would shut it down immediately.

Doing the install from python worked like a charm.

**Comment by buthig666** [comment]
Go into your windows security and reinstate the file from quarantine, and allow it.

**Comment by HarryAnkers** [comment]
Also watching this. If this can be fixed will download but can't until then :/

**Comment by LeGeRyChEeSe** [comment]
If anyone knows how to create an executable file from python without having false positives, I'm interested.

**Comment by TheMaxik** [comment]
@LeGeRyChEeSe I think you need to sign your executable with a Codesigning Certificate that is trusted by default. You can buy this type of Certificate at Globaltrustpoint. The best way would be not to use a Py to Exe Converter. These pack the Python into the .exe (thats what malware also does).
Maybe you can make a installer PowerShell script, that downloades Python runtime for you and uses it live without installing.

No .exe but also no Defender Problems.

**Comment by LeGeRyChEeSe** [comment]
Hello thank you for the tips. I will take a look.

**Comment by LeGeRyChEeSe** [comment]
Issue fixed - See 2e445ff
